---
apiVersion: v1
kind: Namespace
metadata:
  name: hotel-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hotel-app
  name: deployment-hotel-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hotel-app
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hotel-app
    spec:
      containers:
      - image: sreedhar8897/hotel-booking-app:latest
        imagePullPolicy: Always
        name: hotel-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: hotel-app
  name: service-hotel-app
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: hotel-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: hotel-app
  name: ingress-hotel-app
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-hotel-app
              port:
                number: 80
